#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID -x /usr/bin/clayd`
case "$1" in
  start)
    stat_busy "Starting Clay Daemon"
    if [ -z "$PID" ]; then 
       /usr/bin/clayd
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID -x /usr/bin/clayd`
      echo $PID > /var/run/clayd.pid
      add_daemon clayd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Clay Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon clayd
      rm -f /var/run/clayd.pid
      stat_done
    fi
    ;;
  restart)
    $0 stop
    if [ ! -z $PID ]; then
      while ps -p $PID > /dev/null; do sleep 1; done
    fi
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
