#!/usr/bin/env python2
'''
The virtual machine manager for clay
'''

import clay
import clay.utils

def main():
    '''
    The main function
    '''
    vm = clay.ClayVM()
    clay.utils.check_root()
    vm.clay_vm()


if __name__ == '__main__':
    main()
